### ISSUE TITLE
Описание списочных (list) методов.

### ISSUE THREAD

**Issue by roganbornn** [bitrix-tools/b24-rest-docs#11]
Добрый день! 
Просьба в каждом list-методе (crm.deal.list / crm.contact.list) и так далее, указывать какие параметры можно передавать на вход. 
И не только основные параметры, как select, filter, order и так далее, а еще и такие интересные вещи как logic. 
Очень хочется в принципе иметь понимание о том, какие параметры доступны в каком методе. 
(Ну или если они доступны в каждом list методе, то сделать единую страницу с описанием параметров list методов.)

**Comment by serg-vostrikov-bitrix** [comment]
опция logic недоступна в старых методах crm, увы.  именно поэтому сразу рекомендуется использовать универсальные методы crm.item.* 

https://apidocs.bitrix24.ru/api-reference/crm/index.html

**Comment by serg-vostrikov-bitrix** [comment]
По остальным методам постепенно дополняем информацию. Если у метода есть плашка 

<img width="828" alt="image" src="https://github.com/user-attachments/assets/9864d756-da20-4950-9849-cad64adbf6ae">

Значит, туда еще не добрались с доделками

**Comment by roganbornn** [comment]
> опция logic недоступна в старых методах crm, увы. именно поэтому сразу рекомендуется использовать универсальные методы crm.item.*
> 
> https://apidocs.bitrix24.ru/api-reference/crm/index.html

Подскажите, а в последствии "Старые" методы, которые заменены универсальными уйдут раздел с устаревшими? Как скоро это случится? Универсальные методы хороши, но они отличаются по ответу от "Старых", если старые не будут переделаны на новые, то нужно будет взаимодействовать с системой в нескольких форматах (Как минимум часть запросов формировать в camelCase а другую часть в UPER_CASE), что вызывает неудобства.
