### ISSUE TITLE
calendar.event.add

### ISSUE THREAD

**Issue by H4RDL1FE** [bitrix-tools/b24-rest-docs#13]
На данный момент данный метод не поддерживает добавление CRM сущности через REST API.
Просьба добавить, если такое возможно. 
Спасибо

**Comment by serg-vostrikov-bitrix** [comment]
Этот метод действительно не поддерживает добавление связи с сущностью CRM. Если разработка метод поменяет, то, конечно, это найдет отражение в документации. Но коллеги, здесь issues относительно документации, а не относительно пожеланий к rest api в целом 😀
