### ISSUE TITLE
imopenlines.crm.chat.user.delete / add - ошибка параметров

### ISSUE THREAD

**Issue by H4RDL1FE** [bitrix-tools/b24-rest-docs#14]
В описании методов на страницах:

1. https://apidocs.bitrix24.ru/api-reference/imopenlines/openlines/chats/imopenlines-crm-chat-user-add.html
2. https://apidocs.bitrix24.ru/api-reference/imopenlines/openlines/chats/imopenlines-crm-chat-user-delete.html

Ошибка в описании метода
Вместо CRM_ENTITY_ID* нужно передавать CRM_ENTITY*

**Comment by serg-vostrikov-bitrix** [comment]
Поправили
