### ISSUE TITLE
Поиск вообще не работает

### ISSUE THREAD

**Issue by darkvovich** [bitrix-tools/b24-rest-docs#20]
![image](https://github.com/user-attachments/assets/0163da9c-c990-44bb-abb4-4d50788805d6)

**Comment by serg-vostrikov-bitrix** [comment]
ну, не то, чтобы совсем не работает. но из-за особенностей поискового индекса, не всегда хорошо ищет непосредственно по названию метода

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/6c0b52f2-0c59-498f-8c9b-b0e386e4039f">

пытаемся найти какое-то решение для этого

**Comment by darkvovich** [comment]
Понятно, ну это же мега важно искать по названию метода!

**Comment by serg-vostrikov-bitrix** [comment]
полечили

**Comment by darkvovich** [comment]
> полечили

Шикарно! Спасибо
