### ISSUE TITLE
Метод crm.timeline.logmessage.list не работает и не до конца задокументирован

### ISSUE THREAD

**Issue by darkvovich** [bitrix-tools/b24-rest-docs#21]
Согласно документации выполняю запрос https://apidocs.bitrix24.ru/api-reference/crm/timeline/logmessage/crm-timeline-logmessage-list.html

Request
```
request('crm.timeline.logmessage.list', [
    	'entityTypeId' => 2, 
    	'entityId' => 263195
])
```
Result
```
Array
(
    [result] => Array
        (
            [logMessages] => Array
                (
                )

        )

    [total] => 0
    [time] => Array
        (
            [start] => 1726054009.154
            [finish] => 1726054009.1883
            [duration] => 0.034317970275879
            [processing] => 0.0035309791564941
            [date_start] => 2024-09-11T14:26:49+03:00
            [date_finish] => 2024-09-11T14:26:49+03:00
            [operating_reset_at] => 1726054609
            [operating] => 0
        )

)
```

Получаю в ответ пустоту, хотя в Сделке есть в таймлайне много событий. Scope CRM стоит.

+ к тому же в доку не описано что за  [logMessages] => Array
??? в примерах выдается сразу result => array

**Comment by darkvovich** [comment]
В старой доке в комментариях люди также пишут что не работает https://dev.1c-bitrix.ru/rest_help/crm/timeline/crm_timeline_logmessage.php (от 2023 г)

**Comment by darkvovich** [comment]
В чатах пишут, что этот метод возвращает только те записи, которые созданы этими же методами. Системные - не возвращаются!

Если это так - хорошо бы написать об этом.

**Comment by serg-vostrikov-bitrix** [comment]
Да, к сожалению, это так - метод видит только записи, добавленные этими же методами. Добавили информацию в описание
