### ISSUE TITLE
Битые ссылки

### ISSUE THREAD

**Issue by ilyailyushko** [bitrix-tools/b24-rest-docs#33]
ссылки в этой статье,  https://github.com/bitrix-tools/b24-rest-docs/blob/c18ccc05164381a15c92a1cbcaf04bdd8eacad12/first-rest-api-call.md?plain=1#L7 
в блоке **примечане**, ведут на 404

-  [тиражное решения](./market/) для размещения в Битрикс24 Маркет...
- [авторизацию OAuth 2.0](./api-reference/oauth/)...

**Comment by vk-bitrix-doc** [comment]
Благодарю, поправили ссылки в статье.
