### ISSUE TITLE
Не работает параметр start в методе user.get

### ISSUE THREAD

**Issue by VadimGareev** [bitrix-tools/b24-rest-docs#36]
Пробовал так, но ничего не получается, передаваемые параметр start точно верный
```javascript
function loadAllEmployees(start = 0) {
    BX24.callMethod('user.get', { 
        FILTER: { "ACTIVE": 'Y' }, 
        start: start // тут пробовал даже указать вручную цифру, пробовал брать в кавычки, пробовал применять все параметры, ничего не помогает, как будто он просто не определяется и всегда возвращается первые 50 элементов
    }, function(res) {
        const employees = res.answer.result;
        // Проверяем, нужно ли загружать следующую порцию данных
        if (res.answer.next) {
            loadAllEmployees(res.answer.next);
        } else {
            console.log("Все сотрудники загружены.");
        }
    });
}
```

**Comment by vk-bitrix-doc** [comment]
Добрый день! В документации мы не консультируем по вопросам работы с rest api. В issues мы правим неточности в содержании статей. Параметр start в методе user.ger верный.

Пожалуйста, для консультации по вашему вопросу напишите в чат коммьюнити https://t.me/bit24dev или создайте обращение в техническую поддержку на вашем портале https://helpdesk.bitrix24.ru/open/17410400/ . Ваш вопрос должен рассматривать технический специалист имея доступ к вашему порталу, чтобы проверить почему параметр в вашем случае не отрабатывает.

https://apidocs.bitrix24.ru/support.html
