### ISSUE TITLE
добавить страницы для генерации примеров по методам из SDK

### ISSUE THREAD

**Issue by mesilov** [bitrix-tools/b24-rest-docs#43]
crm.dealcategory.add
crm.dealcategory.default.get
crm.dealcategory.default.set
crm.dealcategory.delete
crm.dealcategory.get
crm.dealcategory.list
crm.dealcategory.stage.list
crm.dealcategory.update
crm.duplicate.findbycomm
telephony.externalCall.attachRecord
telephony.externalLine.add
telephony.externalLine.get
userconsent.agreement.list

**Comment by vk-bitrix-doc** [comment]
Страницы по методам в документации: 

crm.dealcategory.add — https://apidocs.bitrix24.ru//api-reference/crm/outdated/category-old/crm-deal-category-add.html 
crm.dealcategory.default.get — https://apidocs.bitrix24.ru//api-reference/crm/outdated/category-old/crm-deal-category-default-get.html
crm.dealcategory.default.set — https://apidocs.bitrix24.ru//api-reference/crm/outdated/category-old/crm-deal-category-default-set.html
crm.dealcategory.delete — https://apidocs.bitrix24.ru//api-reference/crm/outdated/category-old/crm-deal-category-delete.html
crm.dealcategory.get — https://apidocs.bitrix24.ru//api-reference/crm/outdated/category-old/crm-deal-category-get.html
crm.dealcategory.list — https://apidocs.bitrix24.ru//api-reference/crm/outdated/category-old/crm-deal-category-list.html
crm.dealcategory.stage.list — https://apidocs.bitrix24.ru//api-reference/crm/outdated/category-old/crm-deal-category-stage-list.html
crm.dealcategory.update — https://apidocs.bitrix24.ru//api-reference/crm/outdated/category-old/crm-deal-category-update.html
crm.duplicate.findbycomm — https://apidocs.bitrix24.ru//api-reference/crm/duplicates/crm-duplicate-find-by-comm.html
telephony.externalCall.attachRecord — https://apidocs.bitrix24.ru//api-reference/telephony/telephony-external-call-attach-record.html
telephony.externalLine.add — https://apidocs.bitrix24.ru//api-reference/telephony/telephony-external-line-add.html
telephony.externalLine.get — https://apidocs.bitrix24.ru//api-reference/telephony/telephony-external-line-get.html
userconsent.agreement.list — https://apidocs.bitrix24.ru//api-reference/user-consent/user-consent-agreement-list

Папки с файлами этих методов: 

https://github.com/bitrix-tools/b24-rest-docs/tree/main/api-reference/crm/outdated/category-old
https://github.com/bitrix-tools/b24-rest-docs/blob/main/api-reference/crm/duplicates/crm-duplicate-find-by-comm.md
https://github.com/bitrix-tools/b24-rest-docs/tree/main/api-reference/telephony
https://github.com/bitrix-tools/b24-rest-docs/blob/main/api-reference/user-consent/user-consent-agreement-list.md 

Все страницы есть. Максим,  уточни, пожалуйста, может нам надо добавить/проверить чтобы было подготовленное место для размещения примеров на них? Там есть одна страница, где раздела примеров нет.
