### ISSUE TITLE
Страница Отправить сообщение в открытую линию imopenlines.crm.message.add | REST API Битрикс24 и приложения для Маркет

### ISSUE THREAD

**Issue by prospektweb** [bitrix-tools/b24-rest-docs#44]
Ссылка на страницу: https://apidocs.bitrix24.ru//api-reference/imopenlines/openlines/messages/index.html

Вероятно, URL должен быть унифицированным?
https://apidocs.bitrix24.ru/api-reference/imopenlines/openlines/messages/imopenlines-crm-message-add.html

**Comment by serg-vostrikov-bitrix** [comment]
@vk-bitrix-doc, кажется, что да, нужна отдельная индексная страница, а описание метода на странице с соответствующим именем файла. иначе потом еще будут сложности с редиректом по названию метода

**Comment by vk-bitrix-doc** [comment]
Создала страницу метода, индексная и метод теперь отдельно  —  https://apidocs.bitrix24.ru//api-reference/imopenlines/openlines/messages/imopenlines-crm-message-add.html 

Спасибо, @prospektweb!
