### ISSUE TITLE
Путаница с CHAT_ID в разных методах

### ISSUE THREAD

**Issue by Sevanbbx** [bitrix-tools/b24-rest-docs#45]
"chat":{'id': <id>} из метода "imconnector.send.messages", и "CHAT_ID" параметр из разных методов ОЛ оказываются - разные вещи. 

"chat":{'id': <id>}  из метода "imconnector.send.messages" -  это SESSION_ID  из метода "imopenlines.dialog.get". 

Так как в методе "imconnector.send.messages" "chat":{'id': <id>} можно легко перепутать с "CHAT_ID" из остальных методов, предлагаю несколько вариантов решения проблемы(Можно применять несколько решений одновременно)

1. Переименовать параметр "chat":{'id': <id>} на "session": {'id': <id>} в методе "imconnector.send.messages" в том числе и в документации, очевидно сохраняя "chat":{'id': <id>} для backward compatibility. Таким образом новички не будут перепутывать понятия, а старые приложения будут работать как раньше.

2. В документации, в самом верхнем разделе добавить энциклопедию, которая объясняет понятия, которые можно перепутать. 

3. Изменить описания параметров "chat":{'id': <id>} в  "imconnector.send.messages" и "CHAT_ID" в других методов ОЛ, с учётов того, что можно их перепутать.

**Comment by vk-bitrix-doc** [comment]
Добрый день! Параметр "chat":{'id': } из метода "imconnector.send.messages", и  параметр "CHAT_ID" из методов ОЛ — это действительно разные значения. 

Метод imconnector.send.messages создает сообщение из внешнего коннектора открытой линии, который зарегистрировало приложение. Массив "chat" в нем заполняется значениями внешнего коннектора. Это ID чата в приложении коннектора, не в Битрикс. 
 
SESSION_ID это ID сессии, диалога внутри чата с пользователем в Битрикс. На момент выполнения метода imconnector.send.messages открытого диалога может не быть. Приложение получает массив "session" с ID диалога, и с CHAT_ID, ID чата с пользователем, внутри Битрикс в результате работы метода imconnector.send.messages.

Благодарю за сообщение! Дополнили статью вводным словом о внешней системе в параметрах метода. https://apidocs.bitrix24.ru/api-reference/imopenlines/imconnector/imconnector-send-messages.html
