### ISSUE TITLE
Добавить событие о завершении диалога OnImopenlinesDialogFinish

### ISSUE THREAD

**Issue by Sevanbbx** [bitrix-tools/b24-rest-docs#46]
Так как есть возможность отправить сообщения в Битрикс24 с помощью метода  "imconnector.send.messages" и есть возможность получить сообщения из Битрикс24 с помощью события "OnImConnectorMessageAdd", не хватает возможности узнавать об окончании диалога, чтобы полностью поддерживать переписку между Битрикс24 и локальным приложением (Оператор - клиент).

**Comment by serg-vostrikov-bitrix** [comment]
Коллеги, с запросами по изменению rest или по багам в rest, надо идти в поддержку. этот репозиторий - документация
