### ISSUE TITLE
Страница Сменить владельца чата im.chat.setOwner | REST API Битрикс24 и приложения для Маркет

### ISSUE THREAD

**Issue by prospektweb** [bitrix-tools/b24-rest-docs#47]
Ссылка на страницу: https://apidocs.bitrix24.ru/api-reference/chats/chat-update/index.html

Ожидаю адрес https://apidocs.bitrix24.ru/api-reference/chats/chat-update/im-chat-set-owner.html

**Comment by vk-bitrix-doc** [comment]
Благодарю! Создала страницу метода, индексная и метод теперь отдельно — https://apidocs.bitrix24.ru/api-reference/chats/chat-update/im-chat-set-owner.html
