### ISSUE TITLE
Страница Отключить уведомления от чата im.chat.mute | REST API Битрикс24 и приложения для Маркет

### ISSUE THREAD

**Issue by prospektweb** [bitrix-tools/b24-rest-docs#48]
Ссылка на страницу: https://apidocs.bitrix24.ru//api-reference/chats/special-operations/index

Ожидаю адрес https://apidocs.bitrix24.ru/api-reference/chats/chat-update/im-chat-mute.html

**Comment by vk-bitrix-doc** [comment]
Благодарю! Создала страницу метода, индексная и метод теперь отдельно — https://apidocs.bitrix24.ru/api-reference/chats/special-operations/im-chat-mute.html
