### ISSUE TITLE
Request for OpenAPI Schema Generation in YAML/JSON Format

### ISSUE THREAD

**Issue by MSITETOP** [bitrix-tools/b24-rest-docs#56]
It would be beneficial to implement automatic generation of OpenAPI schemas in YAML or JSON format. This enhancement would make the documentation easier to understand and more convenient for use in various automation tools.

**Comment by serg-vostrikov-bitrix** [comment]
We're preparing a new version of REST API in Bitrix24, which will support OpenAPI standard from the very beginning. But it's not planned to add generating schemas for the existing REST API version, unfortunately. I can't promise that we will reconsider this, but at least we'll discuss it again with colleagues

**Comment by MSITETOP** [comment]
When is the new API expected to be released?
