### ISSUE TITLE
Страница Изменить сделку crm.deal.update | REST API Битрикс24 и приложения для Маркет

### ISSUE THREAD

**Issue by deiww** [bitrix-tools/b24-rest-docs#58]
Ссылка на страницу: https://apidocs.bitrix24.ru/api-reference/crm/deals/crm-deal-update.html

IS_RETURN_CUSTOMER не получается изменить на финальных стадиях, на рабочих стадиях значение сохраняется только до момента смены стадии. Так что, изменение этого поля вижу бесполезным.

**Comment by serg-vostrikov-bitrix** [comment]
не очень понятно, что вы хотите, чтобы мы по этому поводу сделали в документации? это информационное поле, которое показывает, является ли сделка повторной. всё. она не может быть "не повторной" (ну, то есть, первой сделкой некого покупателя) при создании, а потом вдруг стать повторной.

**Comment by deiww** [comment]
Была задача новые сделки клиентов которые импортированы в Битрикс24, а значит в старой CRM с ними были сделки, помечать как повторные.
Поле readonly = false
а значит его можно изменить, но по факту нельзя.
И такое поведение выяснилось после нескольких часов тестов.
Дабы сэкономить время разработчикам, следовало бы указать, что лучше **этим полем не пользоваться на запись**, так как такое поведение Битрикс24 нигде не описано и непрозрачно.
