### ISSUE TITLE
Page Как получить доступ к REST API? | REST API Битрикс24 и приложения для Маркет

### ISSUE THREAD

**Issue by Max-Liubimov** [bitrix-tools/b24-rest-docs#64]
Page link: https://apidocs.bitrix24.ru/access-to-rest-api.html
Не описана процедура авторизации.

**Comment by serg-vostrikov-bitrix** [comment]
о какой именно процедуре речь?

**Comment by Max-Liubimov** [comment]
Интересует авторизация по токену для регулярной выгрузки данных. Желательно получить постоянный токен. Подходит ли Локальный входящий вебхук для такой задачи?

**Comment by serg-vostrikov-bitrix** [comment]
Получение доступа к ресту и авотризация для вызова метода - разные вещи. https://apidocs.bitrix24.ru/api-reference/how-to-call-rest-api/authorization.html
