### ISSUE TITLE
Page Получить лиды, контакты и компании с совпадающими данными crm.duplicate.findbycomm | REST API Битрикс24 и приложения для Маркет

### ISSUE THREAD

**Issue by vrtem3** [bitrix-tools/b24-rest-docs#72]
Page link: https://apidocs.bitrix24.ru/api-reference/crm/duplicates/crm-duplicate-find-by-comm.html

Добрый день, как можно выполнить поиск дублей контактов с учетом добавочного в номере телефона? 

Насколько я понял - добавочный номер не влияет на поиск дублей.
Я проверял на одном и том же контакте с разными значениями добавочного номера - всегда получаю ID контакта.

Примеры:
+78129999331#404812
+78129999331#4048
+78129999331

**Comment by vk-bitrix-doc** [comment]
Добрый день! 
Пожалуйста, создайте обращение в техническую поддержку на вашем портале — коллеги прикрепят ваше обращение к заявке на расширение функционала поиска дубликатов. Сейчас не только метод crm.duplicate.findbycomm, но и сам функционал поиска дубликатов в Битрикс не учитывает добавочный номер.  

В статье по методу дополнили информацию.
