### ISSUE TITLE
Метод socialnetwork.api.workgroup.get не видит id передаваемый в groupId

### ISSUE THREAD

**Issue by SnakeOwl** [bitrix-tools/b24-rest-docs#74]
Примерно по такой ссылке пытаюсь получить информацию о рабочей группе:
https://[company_name].bitrix24.ru/rest/1/[webhook]/socialnetwork.api.workgroup.get?groupId=98
Ответ:
{
  "error":"SONET_CONTROLLER_WORKGROUP_EMPTY",
  "error_description":"Не передано значение ID рабочей группы."
}

Пожалуйста актуализируйте информацию по этому методу. Возможно там какая-то другая переменная считывается.

ps: метод sonet_group.user.get?ID=98 видит эту группу, так что дело тут точно не в доступах.

**Comment by vk-bitrix-doc** [comment]
Добрый день! Информацию в статье дополнили. Благодарю, что обратили наше внимание на нее :)

Используйте такой формат для вебхука — /socialnetwork.api.workgroup.get?params[groupId]=1
