### ISSUE TITLE
Page Получить товарные позиции объекта CRM crm.item.productrow.list | REST API Битрикс24 и приложения для Маркет

### ISSUE THREAD

**Issue by muravikov** [bitrix-tools/b24-rest-docs#75]
Page link: https://apidocs.bitrix24.ru/api-reference/crm/universal/product-rows/crm-item-productrow-list.html

**=ownerType** хотелось бы снабдить ссылкой https://apidocs.bitrix24.ru/api-reference/crm/data-types.html#object_type  и пояснением что нужен 4й столбец, и что смарты кодируются так:

Чтобы определить префикс смарт-процесса, необходимо:

сконвертировать идентификатор из десятичной системы в шестнадцатеричную. В случае с идентификатором равным 128, получаем значение 80.
взять полученное значение в нижнем регистре и к полученному значению дописать латинскую букву T в начале. Таким образом, получаем префикс — T80.

**Comment by vk-bitrix-doc** [comment]
Добрый день! Дополнили статьи [crm.item.productrow.add](https://apidocs.bitrix24.ru/api-reference/crm/universal/product-rows/crm-item-productrow-add.html), [crm.item.productrow.set](https://apidocs.bitrix24.ru/api-reference/crm/universal/product-rows/crm-item-productrow-set.html), [crm.item.productrow.list](https://apidocs.bitrix24.ru/api-reference/crm/universal/product-rows/crm-item-productrow-list.html) и [crm.item.productrow.getAvailableForPayment](https://apidocs.bitrix24.ru/api-reference/crm/universal/product-rows/crm-item-productrow-get-available-for-payment.html) ссылкой на https://apidocs.bitrix24.ru/api-reference/crm/data-types.html#object_type и указанием, что необходимо использовать Краткий символьный код типа. 

Дополнение про префикс смарт-процессов находится сразу под таблицей типов объектов, его в статьи не дублируем. 

Благодарю за обратную связь!
