### ISSUE TITLE
Получение прикреплённых к задаче файлов

### ISSUE THREAD

**Issue by SnakeOwl** [bitrix-tools/b24-rest-docs#76]
Где описан метод получения прикреплённых к задаче файлов? 
Нашёл этот: [task.item.getfiles](https://apidocs.bitrix24.ru/api-reference/tasks/deprecated/task-item/task-item-get-files.html) , но он помечен как устаревший (хотя работает).

Актуализируйте пожалуйста информацию.

**Comment by vk-bitrix-doc** [comment]
Добрый день! Метод [tasks.task.get](https://apidocs.bitrix24.ru/api-reference/tasks/tasks-task-get.html) вернет  ID связи, которая соединяет задачу и файл диска. Укажите поле UF_TASK_WEBDAV_FILES в SELECT, без этого метод поле не отдаст.

Для получения информации о файле по ID связи используйте метод [disk.attachedObject.get](https://apidocs.bitrix24.ru/api-reference/disk/attached-object/disk-attached-object-get.html). 

Данная информация описана в туториале [Как создать задачу с прикрепленным файлом](https://apidocs.bitrix24.ru/tutorials/tasks/how-to-create-task-with-file.html). 

Отдельного метода для получения файлов задачи нет среди tasks.task.*. Вы можете использовать task.item.getfiles, на текущий момент метод работает.
