### ISSUE TITLE
Page Вкладка в детальной карточке элемента CRM CRM_XXX_DETAIL_TAB, CRM_DYNAMIC_XXX_DETAIL_TAB | REST API Битрикс24 и приложения для Маркет

### ISSUE THREAD

**Issue by voronrk** [bitrix-tools/b24-rest-docs#78]
Page link: https://apidocs.bitrix24.ru/api-reference/widgets/crm/detail-tab.html

Ссылки ведут на 404. Причём, если кликать колесом (открытие в другой вкладке), то всё открывается нормально, а если кнопкой (открыть в текущей вкладке), то 404.
Клик колесом ведёт на https://apidocs.bitrix24.ru/api-reference/crm/leads/
Клик клавишей ведёт на https://apidocs.bitrix24.ru/api-reference/crm/leads.html
С остальными ссылками то же

**Comment by serg-vostrikov-bitrix** [comment]
Да, занимаемся уже
